services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      ai-blog-db:
        condition: service_healthy
    links:
      - ai-blog-db
    networks:
      - app-network

  ai-blog-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai-blog-db
    ports:
      - "5432:5432"
    volumes:
      - ai-blog-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ai-blog-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  app-network:
    driver: bridge

volumes:
  ai-blog-db-data: